// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace HexFall
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;
		public AudioClip winSound;
		public AudioClip loseSound;
		public AudioClip coinSound;
		public AudioClip brickSound;
	}
}